// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ihbHJHdZcR4JHjZVmq8i-nrkdx8WVqQ',
    appId: '1:913530838601:web:96a2c6ca3c54ffba44e998',
    messagingSenderId: '913530838601',
    projectId: 'cinespot-1',
    authDomain: 'cinespot-1.firebaseapp.com',
    storageBucket: 'cinespot-1.firebasestorage.app',
    measurementId: 'G-GBR0R83FVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17J1Nk2YdOhUKPNPPzdq6ih63g5Z9CtE',
    appId: '1:913530838601:android:9115deb385c870c244e998',
    messagingSenderId: '913530838601',
    projectId: 'cinespot-1',
    storageBucket: 'cinespot-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcnh-duxgGm7eSWd-tQG6sJNYIFDvke8',
    appId: '1:913530838601:ios:1cee290a033576f644e998',
    messagingSenderId: '913530838601',
    projectId: 'cinespot-1',
    storageBucket: 'cinespot-1.firebasestorage.app',
    iosBundleId: 'com.example.cineSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVcnh-duxgGm7eSWd-tQG6sJNYIFDvke8',
    appId: '1:913530838601:ios:1cee290a033576f644e998',
    messagingSenderId: '913530838601',
    projectId: 'cinespot-1',
    storageBucket: 'cinespot-1.firebasestorage.app',
    iosBundleId: 'com.example.cineSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ihbHJHdZcR4JHjZVmq8i-nrkdx8WVqQ',
    appId: '1:913530838601:web:a09e16c9af0e8bbf44e998',
    messagingSenderId: '913530838601',
    projectId: 'cinespot-1',
    authDomain: 'cinespot-1.firebaseapp.com',
    storageBucket: 'cinespot-1.firebasestorage.app',
    measurementId: 'G-6SXNWCDS07',
  );
}
